services:
  - type: web
    name: kidai-backend
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn kidai_backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: IS_PRODUCTION
        value: True
      - key: ALLOWED_HOSTS
        value: kidai-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-vercel-app.vercel.app
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
    healthCheckPath: /health/ 